### PR TITLE
Feature/update docs

### PR DESCRIPTION
**Pull request by christian-krieg**
As promised, here is also the PR that updates the documentation for my previous fix.
@escopecz it would be very cool if you could update the plugin at the official Grav site; at the moment, there is a very outdated version of the plugin, which doesn't even support DWC...

Thanks a l lot in advance!

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks @christian-krieg for making the PR! I think we should be able to make a new release, although we haven't got any actions set up so it will be a manual process for the time being :)

**Review by escopecz — APPROVED** [review]
👍

**Comment by escopecz** [comment]
@christian-krieg do you have an ambition to become one of the maintainers of this repo so you could prepare new versions?

**Comment by christian-krieg** [comment]
@escopecz Thank you very much for considering me becoming one of the maintainers; I would highly appreciate that!

**Comment by escopecz** [comment]
Great news! I sent you an invitation. Let me know if you need any help.

**Pull request merged**
