### PR TITLE
Adding support for assets

### PR DESCRIPTION
**Pull request by christian-krieg**
* Asset links are now supported via Mautic shortcodes
* An additional `alias` parameter is used to generate the asset link
* Updated `README.md` to document the feature
* Updated `CHANGLELOG.md` and `blueprints.yaml` to update the package

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
I see no issue within the code changes. Thanks! 👍

**Comment by christian-krieg** [comment]
Cool, thanks for the review! Could you please also do the merge? Apparently I don't have the rights to do so.

**Comment by escopecz** [comment]
I wish we had some active users of this plugin available to test this. But since it looks like you are the only one and I see no issue in the code, I'll hit the button. Thanks for this!

**Comment by christian-krieg** [comment]
Unfortunately, the plugin never really worked until I fixed it. Probably, in the past, potential users may have had a look at it, found it non-functional, and never started using it. Hopefully this may change in the future, as it adds a lot of value to Grav-based sites.

**Pull request merged**
