### PR TITLE
Feat/unify interface

### PR DESCRIPTION
**Pull request by christian-krieg**
Introduced unified (and simplified) shortcode interface
    
* Instead of having different parameters for different types of content IDs
  (e.g., "slot" for DWC slot name, or "item" for focus item ID), a general "id"
  parameter has been introduced, which is evaluated depending in the "type"
  parameter
    
* A shortcode syntax is introcuded for form embeds in addition to the
  Markdown link syntax

### CODE REVIEW

**Comment by RCheesley** [comment]
@christian-krieg please can you ensure that we are getting reviews on these PRs before merging. For example this is a community plugin therefore it is not appropriate for you to add copyright notices to the plugin.

@escopecz is probably the most appropriate for doing code reviews with you.

@escopecz please take a look at the most recently reviewed PRs and raise an issue for any changes which are required.

**Comment by christian-krieg** [comment]
@RCheesley sure, I would be happy to follow any policy you set up for this repo. I just added the copyright notice into the LICENSE file because I'm used to do so in my other projects (assuming common practice), but I would be more than happy to follow your guidelines instead.
Just let me know how to proceed!

**Comment by christian-krieg** [comment]
@RCheesley I am sorry for any inconvenience my pro-activeness may have caused; I thought the idea of making me a maintainer is to save time on your side, so I took the chance to significantly work on the plugin.

Please be assured that I carefully tested any bugfix I carried out, as well as the additional features I implemented to make it more convenient for Grav users to use Mautic on their sites.

Anyway, in the future I'll continue pushing by changes into feature branches instead of directly pushing to the main branch. Due to the (almost absent) activity I assumed I would be the only one actively working on that  project right now. Of course, there was no reason to make such an assumption.

Happily looking forward to your reviews!

**Comment by RCheesley** [comment]
No problems at all - we should have had the branch protection rules in place but the repo has been dormant for some time so we hadn't updated them! 😊   I have added them now and we will also get pinged in our notifications channel on Slack so it will be more visible!

Yes please do use branches - here is our documentation: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests.

Although you are the only one actively working on it, we do have a duty of care to our users to review changes (especially from new contributors) before they are deployed out to the world. You can use the @ mautic/triage-team or mautic/core-team group if you need any reviews carried out or just ping us in Slack (you can get an invite at https://mautic.org/slack) in #t-product. We have a sprint each Friday so that is when there will be folks about who can help.

Thanks again for being willing to get things up and running again with the plugin .. we should probably deploy it on our own Mautic Community Grav instances!

**Comment by christian-krieg** [comment]
Cool, thanks a lot for the pointers! Yeah, the plugin is really cool and it's amazing what you can do with Mautic! Although I had some difficulties in the beginning to get it up and running, I'm just falling in love with it <3

Thanks a lot for all the amazing work you put into Mautic!

**Comment by escopecz** [comment]
Thanks @christian-krieg!

There are 2 issues with this PR:
1. There is no need to add yourself to the contributors as it is visible in https://github.com/mautic/mautic-grav/graphs/contributors when and how much you contributed. You can imagine that adding all contributors to the file for more active repos would be inconvenient.
2.  I'm afraid about backward compatibility here. From the code change I understand that the current short codes will stop working once users upgrade the plugin. Do I read it right?

**Comment by escopecz** [comment]
I just noticed you already thought about the second point with https://github.com/mautic/mautic-grav/pull/11

**Comment by christian-krieg** [comment]
@escopecz Thanks for your review!

Fully get your point! I just would like to know how we proceed regarding the copyright notice? Shall I file another PR with the noticed removed in the LICENSE file?

**Comment by escopecz** [comment]
@christian-krieg Either a new PR or sneak a commit with it to your existing open PR. Whatever you think is best.

**Comment by christian-krieg** [comment]
@escopecz Great, I'll go with the second option then and will sneak a commit into #11  :)

**Pull request merged**
