### PR TITLE
Fixing GPM issues

### PR DESCRIPTION
**Pull request by christian-krieg**
* Fixing multi-line YAML field value
* Bringing CHANGELOG into newest-first order

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
Do you think this PR could also bump the version as recommended in https://github.com/mautic/mautic-grav/issues/12#issuecomment-1084815344 ?

**Comment by christian-krieg** [comment]
Done; I updated the CHANGELOG including the unified shortcode interface, so I updated the version number to 1.4.0. I also created a tag -- so once the PR is merged, I will create a release so that it can be tested by @w00fz

**Comment by christian-krieg** [comment]
@escopecz is there anything else to be done for this PR?

**Review by escopecz — APPROVED** [review]
Looks great. Thanks for taking care of that! 👍 

_Sorry for late reply. I was at a conference last week_

**Comment by christian-krieg** [comment]
Cool, thx a lot! I'm going to create a release, so it can be tested for compliance with GPM.

**Pull request merged**
